# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

places:
    type:     rest
    resource: App\Controller\PlaceController
prices:
    type:     rest
    resource: App\Controller\PriceController

users:
    type:     rest
    resource: App\Controller\UserController   

auth-tokens:
    type:     rest
    resource: App\Controller\AuthTokenController    
    
themes:
    type:     rest
    resource: App\Controller\ThemeController

preferences:
    type:     rest
    resource: App\Controller\PreferenceController    

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /documentation    